# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  sam-dfo-sw-api

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html

Resources:
  # This is a Lambda function config associated with the source code: get-all-items.js
  GetAssociatedAssets:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ssc-dfo-sam-sw-api-getAssociatedAssets
      Handler: src/handlers/sitewise-handler.getAssociatedAssets
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieve a list of assets associated to a the parent asset from Sitewise.
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Tags:
        cdxp:owner: chobbins
        cdxp:env: sbx
        cdxp:project: dfo
      Events:
        Api:
          Type: Api
          Properties:
            Path: /associated-assets
            Method: GET
            RequestParameters:
              - method.request.querystring.assetIds:
                  Required: true
                  Caching: false
  GetAssetLastLocation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ssc-dfo-sam-sw-api-getAssetLastLocation
      Handler: src/handlers/location-handler.getAssetLastLocation
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieve the last location for tracked assets from Location Service.
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Tags:
        cdxp:owner: chobbins
        cdxp:env: sbx
        cdxp:project: dfo
      Events:
        Api:
          Type: Api
          Properties:
            Path: /asset-locations
            Method: GET
            RequestParameters:
              - method.request.querystring.tracker:
                  Required: true
                  Caching: false
              - method.request.querystring.assetIds:
                  Required: true
                  Caching: false
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
